### PR TITLE
Import configuration

### PR DESCRIPTION
**Pull request by sbesson**
Changes matching the import options introduced in https://github.com/openmicroscopy/openmicroscopy/pull/5828

### CODE REVIEW

**Comment by sbesson** [comment]
A few images are missing from `filePaths.tsv`. but https://web-proxy.openmicroscopy.org/east-ci/job/IDR-import/12/consoleText was the baseline for the import of idr0021 without these changes i.e. 20min for a sequential import with no import step skipped and with this included.
With this PR included, this drops to 3min - see https://web-proxy.openmicroscopy.org/east-ci/job/IDR-import/28/.

**Comment by pwalczysko** [comment]
Command

``/opt/omero/server/OMERO.server/bin/omero load test-seb/idr0021-experimentA-containers.omero`` went fine

Follow-up command

``/opt/omero/server/OMERO.server/bin/omero  import --bulk test-seb/idr0021-experimentA-bulk.yml``

failed to import


```
2018-12-13 13:56:04,983 175        [      main] INFO          ome.formats.importer.ImportConfig - OMERO Version: 5.4.9-ice36-b101
2018-12-13 13:56:04,994 186        [      main] INFO          ome.formats.importer.ImportConfig - Bioformats version: 5.9.2 revision: 9fc607f85b8900be786813296f1eee75cc1ed883 date: 31 August 2018
2018-12-13 13:56:05,025 217        [      main] INFO   formats.importer.cli.CommandLineImporter - Setting checksum algorithm to File-Size-64
2018-12-13 13:56:05,026 218        [      main] INFO   formats.importer.cli.CommandLineImporter - Skipping thumbnails creation
2018-12-13 13:56:05,026 218        [      main] INFO   formats.importer.cli.CommandLineImporter - Skipping minimum/maximum computation
2018-12-13 13:56:05,026 218        [      main] INFO   formats.importer.cli.CommandLineImporter - Disabling upgrade check
2018-12-13 13:56:05,026 218        [      main] INFO   formats.importer.cli.CommandLineImporter - Setting parallel upload: 20
2018-12-13 13:56:05,026 218        [      main] INFO   formats.importer.cli.CommandLineImporter - Setting transfer to ln_s
2018-12-13 13:56:05,027 219        [      main] ERROR  formats.importer.cli.CommandLineImporter - Conflicting arguments setting checksumAlgorithm.

 Usage:  importer-cli [OPTION]... [path [path ...]]... 
   or:   importer-cli [OPTION]... - 

Import any number of files into an OMERO instance.
If "-" is the only path, a list of files or directories 
is read from standard in. Directories will be searched for 
all valid imports.

Session arguments:
  Mandatory arguments for creating a session are 1- either the OMERO server hostname,
username and password or 2- the OMERO server hostname and a valid session key.
  -s SERVER	OMERO server hostname
  -u USER	OMERO username
  -w PASSWORD	OMERO password
  -k KEY	OMERO session key (UUID of an active session)
  -p PORT	OMERO server port (default: 4064)

Naming arguments:
All naming arguments are optional
  -n NAME				Image or plate name to use
  -x DESCRIPTION			Image or plate description to use
  --name NAME				Image or plate name to use
  --description DESCRIPTION		Image or plate description to use

Optional arguments:
  -h					Display this help and exit
  -f					Display the used files and exit
  -c					Continue importing after errors
  -l READER_FILE			Use the list of readers rather than the default
  -d DATASET_ID				OMERO dataset ID to import image into
  -r SCREEN_ID				OMERO screen ID to import plate into
  -T TARGET				target for imports
  --report				Report errors to the OME team
  --upload				Upload broken files and log file (if any) with report. Required --report
  --logs				Upload log file (if any) with report. Required --report
  --email EMAIL				Email for reported errors. Required --report
  --debug LEVEL				Turn debug logging on (optional level)
  --annotation-ns ANNOTATION_NS		Namespace to use for subsequent annotation
  --annotation-text ANNOTATION_TEXT	Content for a text annotation
  --annotation-link ANNOTATION_LINK	Comment annotation ID to link all images to

Examples:

  $ importer-cli -s localhost -u user -w password -d 50 foo.tiff
  $ importer-cli -s localhost -u user -w password -d Dataset:50 foo.tiff
  $ importer-cli -f foo.tiff
  $ importer-cli -s localhost -u username -w password -d 50 --debug ALL foo.tiff

For additional information, see:
https://docs.openmicroscopy.org/latest/omero/users/cli/import.html
Report bugs to <ome-users@lists.openmicroscopy.org.uk>
Import failed with error code: 1. Continuing
18 failed imports
```

**Comment by pwalczysko** [comment]
Removal of the line containing

``File size-64`` from the ``...bulk.yml`` solved the problem https://github.com/IDR/idr0021-lawo-pericentriolarmaterial/pull/3#issuecomment-446978088

**Comment by pwalczysko** [comment]
Now, I have

```
 ome.formats.OMEROMetadataStoreClient - OS Version: 3.10.0-514.21.1.el7.x86_64
2018-12-13 14:07:55,369 1756       [      main] INFO          ome.formats.importer.ImportConfig - Using import target: Dataset:name:CDK5RAP2-C
2018-12-13 14:07:55,369 1756       [      main] INFO          ome.formats.importer.ImportConfig - Using import target: Dataset:name:CDK5RAP2-C
2018-12-13 14:07:55,370 1757       [      main] INFO          ome.formats.importer.ImportConfig - Using import target: Dataset:name:CDK5RAP2-C
2018-12-13 14:07:55,370 1757       [      main] INFO          ome.formats.importer.ImportConfig - Using import target: Dataset:name:CDK5RAP2-C
2018-12-13 14:07:55,370 1757       [      main] INFO          ome.formats.importer.ImportConfig - Using import target: Dataset:name:CDK5RAP2-C
2018-12-13 14:07:55,370 1757       [      main] INFO          ome.formats.importer.ImportConfig - Using import target: Dataset:name:CDK5RAP2-C
2018-12-13 14:07:55,370 1757       [      main] INFO          ome.formats.importer.ImportConfig - Using import target: Dataset:name:CDK5RAP2-C
2018-12-13 14:07:55,448 1835       [2-thread-7] INFO   ormats.importer.cli.LoggingImportMonitor - FILESET_UPLOAD_PREPARATION
2018-12-13 14:07:55,451 1838       [2-thread-2] INFO   ormats.importer.cli.LoggingImportMonitor - FILESET_UPLOAD_PREPARATION
2018-12-13 14:07:55,451 1838       [2-thread-4] INFO   ormats.importer.cli.LoggingImportMonitor - FILESET_UPLOAD_PREPARATION
2018-12-13 14:07:55,451 1838       [2-thread-1] INFO   ormats.importer.cli.LoggingImportMonitor - FILESET_UPLOAD_PREPARATION
2018-12-13 14:07:55,453 1840       [2-thread-6] INFO   ormats.importer.cli.LoggingImportMonitor - FILESET_UPLOAD_PREPARATION
2018-12-13 14:07:55,457 1844       [2-thread-5] INFO   ormats.importer.cli.LoggingImportMonitor - FILESET_UPLOAD_PREPARATION
2018-12-13 14:07:55,458 1845       [2-thread-3] INFO   ormats.importer.cli.LoggingImportMonitor - FILESET_UPLOAD_PREPARATION
2018-12-13 14:07:55,852 2239       [2-thread-1] ERROR        ome.formats.importer.ImportLibrary - Error on import: could not insert: [ome.model.core.OriginalFile]; SQL [insert into originalfile (atime, ctime, creation_id, external_id, group_id, owner_id, permissions, update_id, hash, hasher, mimetype, mtime, name, path, repo, "size", version, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; constraint [originalfile_repo_path_index]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [ome.model.core.OriginalFile]
omero.ValidationException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_131]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_131]
	at IceInternal.BasicStream.createUserException(BasicStream.java:2779) ~[ice.jar:na]
	at IceInternal.BasicStream.access$300(BasicStream.java:14) ~[ice.jar:na]
	at IceInternal.BasicStream$EncapsDecoder10.throwException(BasicStream.java:3298) ~[ice.jar:na]
	at IceInternal.BasicStream.throwException(BasicStream.java:2291) ~[ice.jar:na]
	at IceInternal.OutgoingAsync.throwUserException(OutgoingAsync.java:399) ~[ice.jar:na]
	at omero.grid.ManagedRepositoryPrxHelper.end_importFileset(ManagedRepositoryPrxHelper.java:175) ~[blitz.jar:na]
	at omero.grid.ManagedRepositoryPrxHelper.importFileset(ManagedRepositoryPrxHelper.java:46) ~[blitz.jar:na]
	at omero.grid.ManagedRepositoryPrxHelper.importFileset(ManagedRepositoryPrxHelper.java:33) ~[blitz.jar:na]
	at ome.formats.importer.ImportLibrary.createImport(ImportLibrary.java:420) ~[blitz.jar:na]
	at ome.formats.importer.ImportLibrary.importImage(ImportLibrary.java:563) ~[blitz.jar:na]
	at ome.formats.importer.ImportLibrary$1.call(ImportLibrary.java:306) [blitz.jar:na]
	at ome.formats.importer.ImportLibrary$1.call(ImportLibrary.java:286) [blitz.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
...
```

There are other 2 repetitions of the similar error. After that, the whole import seems to have proceeded as expected. Nevertheless, the 3 errors indicate that 3 images were not imported, namely in the first dataset, ``CDK....`` . Indeed, as far as I know, this dataset is supposed to have 33 images. But, after this import, it has only 30.

**Comment by pwalczysko** [comment]
Setting the parameter
https://github.com/IDR/idr0021-lawo-pericentriolarmaterial/pull/3/files#diff-d81e62f2716c83f7f64394876b825d74R10

to 5 instead of 20


fixed the problem with crashing on 3 images https://github.com/IDR/idr0021-lawo-pericentriolarmaterial/pull/3#issuecomment-446983561

but, not completely sure why is the order of the parameters in the ``...bulk.yml`` as 
1. ``--parallel-upload``
2. ``--parallel-fileset``

According to the doc http://docs.openmicroscopy.org/omero/5.4.9/users/cli/import.html?highlight=parallel#cmdoption-omero-import-parallel-fileset and intuitively (the ``parallel upload`` should be at least as high as the ``parallel fileset``, as the doc says, which makes it more natural workflow to set up first Ad 2., then Ad 1.), it would make sense to swap those two lines.

**Comment by pwalczysko** [comment]
two cleanup suggestions of the ``bulk.yml``.

otherwise works nicely.

**Comment by pwalczysko** [comment]
Some questions regarding the rendering of the .tiff images inside the ``NEDD...`` dataset.

**Comment by sbesson** [comment]
@pwalczysko changes pushed to address https://github.com/IDR/idr0021-lawo-pericentriolarmaterial/pull/3#issuecomment-446991365. I expect only skipping the checksum i.e. computing the min/max should reduce the issues with the rendering of the TIFF images. The problem might be that the third channel of these files is completely empty and might cause issues in one of the rendering settings calculation codepath.

**Comment by pwalczysko** [comment]
Now, with the new commits, I have a very good result on one user only.
(user-44).
Now, once done with full success with importing for user-44, I went on to do the same for user-45.
I did the same sequence of commands, namely logging out, loggging in again as importer1 sudoing as user-45, then running the ``load`` command, which I immediately checked in the webclient as being successful. After this, with not too much delaty, I ran the ``import`` command.

I am getting a similar problem as above, with the ``CDK...`` dataset having just 30 images instead of 33. Thsi is caused by an error

```
2018-12-13 17:07:43,210 1873       [2-thread-5] ERROR        ome.formats.importer.ImportLibrary - Error on import: Directory exists but is not registered: CheckedPath(user-45_753/2018-12)
omero.ResourceError: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_131]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_131]
	at IceInternal.BasicStream.createUserException(BasicStream.java:2779) ~[ice.jar:na]
	at IceInternal.BasicStream.access$300(BasicStream.java:14) ~[ice.jar:na]
	at IceInternal.BasicStream$EncapsDecoder10.throwException(BasicStream.java:3298) ~[ice.jar:na]
	at IceInternal.BasicStream.throwException(BasicStream.java:2291) ~[ice.jar:na]
	at IceInternal.OutgoingAsync.throwUserException(OutgoingAsync.java:399) ~[ice.jar:na]
	at omero.grid.ManagedRepositoryPrxHelper.end_importFileset(ManagedRepositoryPrxHelper.java:175) ~[blitz.jar:na]
	at omero.grid.ManagedRepositoryPrxHelper.importFileset(ManagedRepositoryPrxHelper.java:46) ~[blitz.jar:na]
	at omero.grid.ManagedRepositoryPrxHelper.importFileset(ManagedRepositoryPrxHelper.java:33) ~[blitz.jar:na]
	at ome.formats.importer.ImportLibrary.createImport(ImportLibrary.java:420) ~[blitz.jar:na]
...
```

**Comment by pwalczysko** [comment]
The rnd settings are as expected now

**Comment by pwalczysko** [comment]
When trying the import for user-45 the second time, the problem https://github.com/IDR/idr0021-lawo-pericentriolarmaterial/pull/3#issuecomment-447048658 did not repeat, all went fine.
Wonder what will happen if this sequence of commands is inside a loop which iterates over all the users. That is the ultimate goal for me

**Comment by sbesson** [comment]
https://github.com/IDR/idr0021-lawo-pericentriolarmaterial/pull/3#issuecomment-447048658 is a another classic problem associated parallel imports for a given user.

For a server with the default FS repo path template (`%user%_%userId%//%year%-%month%/%day%/%time%`, two concurrent imports under the same user will fail if they try to create one of the following  folders under the `ManagedRepository` at the same time:

- the `YYYY-MM` folder as in https://github.com/IDR/idr0021-lawo-pericentriolarmaterial/pull/3#issuecomment-447048658 (first import of the current month)
- the `YYYY-MM/DD` folder (first import of the current day)
- the `YYYY-MM/DD/HH-mm-ss.SSS` folder (imports happening at the same time at the millesecond precision)

There are really two solutions here:

- either drop the parallelization feature at import time and go back to serial import
- or update the server deployment to support parallel import by adding `%thread%` to the FS repo path - see https://github.com/IDR/deployment/blob/IDR-0.6.0/ansible/group_vars/omero-hosts.yml#L61

Given the reasonably size of this dataset, both options are probably manageable.

**Comment by pwalczysko** [comment]
>see https://github.com/IDR/deployment/blob/v0.6.0/ansible/group_vars/omero-hosts.yml#L61

@sbesson sorry, I cannot find this - the url gives 404 and anytime I try to go beyond ``blob`` it ends there (``https://github.com/IDR/deployment`` is fine)

**Comment by sbesson** [comment]
edited

**Comment by pwalczysko** [comment]
@sbesson See https://github.com/openmicroscopy/prod-playbooks/pull/128

**Comment by pwalczysko** [comment]
Implemented the suggestion 

>or update the server deployment to support parallel import by adding %thread% to the FS repo path - see https://github.com/IDR/deployment/blob/IDR-0.6.0/ansible/group_vars/omero-hosts.yml#L61

and tried to import again for user-44, followed up by import for user-45. All went fine. This here works for me, good improvement, thank you

**Pull request merged**
