### PR TITLE
Modify the import and metadata workflow for Users meeting2018 (2 datasets)

### PR DESCRIPTION
**Pull request by pwalczysko**

### CODE REVIEW

**Comment by jburel** [comment]
Not really part of IDR repo
I think this should go in the training repository https://github.com/ome/training-scripts/tree/master/maintenance/preparation

**Comment by pwalczysko** [comment]
Unfortunately, 

```
bin/omero metadata populate --report --batch 1000 --file /Users/pwalczysko/Work/idr0021-lawo-pericentriolarmaterial/experimentA/idr0021-subset-annotation.csv Project:901

...
INFO:omero.util.populate_metadata:Created new table OriginalFile:42556
INFO:omero.util.populate_metadata:Table initialized with 21 columns.
INFO:omero.util.populate_metadata:Added 32 rows of column data (batch 1)

...

bin/omero metadata populate --context bulkmap --cfg /Users/pwalczysko/Work/idr0021-lawo-pericentriolarmaterial/experimentA/idr0021-bulkmap-config.yml --batch 100 Project:901
Using se8 (user-1@outreach.openmicroscopy.org:4064). Idle timeout: 10 min. Current group: Lab1
Traceback (most recent call last):
  File "bin/omero", line 125, in <module>
    rv = omero.cli.argv()
  File "/Users/pwalczysko/Users-meeting2018/OMERO.server-5.4.6-ice36-b87/lib/python/omero/cli.py", line 1620, in argv
    cli.invoke(args[1:])
  File "/Users/pwalczysko/Users-meeting2018/OMERO.server-5.4.6-ice36-b87/lib/python/omero/cli.py", line 1095, in invoke
    stop = self.onecmd(line, previous_args)
  File "/Users/pwalczysko/Users-meeting2018/OMERO.server-5.4.6-ice36-b87/lib/python/omero/cli.py", line 1172, in onecmd
    self.execute(line, previous_args)
  File "/Users/pwalczysko/Users-meeting2018/OMERO.server-5.4.6-ice36-b87/lib/python/omero/cli.py", line 1254, in execute
    args.func(args)
  File "/Users/pwalczysko/Users-meeting2018/OMERO.server-5.4.6-ice36-b87/lib/python/omero/plugins/metadata.py", line 482, in populate
    options=localcfg)
  File "/Users/pwalczysko/Users-meeting2018/OMERO.server-5.4.6-ice36-b87/lib/python/omero/util/populate_metadata.py", line 1169, in __init__
    self._init_namespace_primarykeys()
  File "/Users/pwalczysko/Users-meeting2018/OMERO.server-5.4.6-ice36-b87/lib/python/omero/util/populate_metadata.py", line 1195, in _init_namespace_primarykeys
    self.client.getSession(), gns, keys)
  File "/Users/pwalczysko/Users-meeting2018/OMERO.server-5.4.6-ice36-b87/lib/python/omero/util/metadata_mapannotations.py", line 220, in add_from_namespace_query
    unwrap(ma.getId()), str(r)))
Exception: Duplicate MapAnnotation primary key: id:9960 ns:openmicroscopy.org/mapr/organism primary:('openmicroscopy.org/mapr/organism', frozenset([('Organism', 'Homo sapiens')])) keyvalues:[('Organism', 'Homo sapiens')] parents:set([]) id:9960
```

Note, we have a duplicate images, albeit for another user, with the same KVPs on the server already. Any remedy ? We need this duplication. cc @joshmoore @sbesson @manics

**Comment by pwalczysko** [comment]
The errror https://github.com/IDR/idr0021-lawo-pericentriolarmaterial/pull/2#issuecomment-390726716 has nothing to do with any duplicated images with duplicated KVPs. I can repeat it on localhost, where there are no such annotations, and even images are not in duplicates.

This must be my ``.csv`` which causes the problem.

**Comment by sbesson** [comment]
@pwalczysko is this still necessary given the latest decision on the content of the Import Workshop?

**Comment by pwalczysko** [comment]
@sbesson Re https://github.com/IDR/idr0021-lawo-pericentriolarmaterial/pull/2#issuecomment-391485947

  - I need to solve the bug https://trello.com/c/kWgFImSC/43-bug-import-target#comment-5b059f818b613a8871a00a4e and thus some renaming might be necessary
  - Need to discuss previous point today
  - @jburel encourages me to open the PR on another repo anyway
  - will migrate everything there, once I establish if and how

**Comment by pwalczysko** [comment]
Replaced by https://github.com/ome/training-scripts/pull/13

**Pull request closed without merging**
